import type { Metadata } from "next"
import localFont from "next/font/local"
import { MuseoModerno } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"

const museoModerno = MuseoModerno({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-museoModerno",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${museoModerno.className} antialiased`}>
        <main>
          <Toaster />
          {children}
        </main>
      </body>
    </html>
  )
}
